---

kind: pipeline
type: docker
name: on-droneci-complete
clone:
  disable: true
steps:
  - name: trigger-github-actions
    image: plugins/webhook
    settings:
      urls:
        - https://api.github.com/repos/code-dot-org/test-workflow-dispatch/actions/workflows/on-droneci-complete.yml/dispatches
      username: x-access-token
      secrets:
        - source: on-droneci-complete-github-token
          target: webhook_password
      template: |
        {
          "ref": "{{ build.branch }}",
          "inputs": {
            "github_sha": "{{ build.commit }}",
            "drone_succeeded": {{ eq build.status 'success' | tojson }}
          }
        }
      debug: true
# depends_on:
#   - unit
#   - ui
trigger:
  event:
    - pull_request
---
kind: signature
hmac: 64f80f45bacfea906a0a36dedfb08b3f5c8394d2aacfb182e6104300965e2bb5

...
