---
name: sleep-for-10s
kind: pipeline
type: docker
clone:
  disable: true
steps:
  - name: sleep
    image: alpine
    commands:
      - sleep 10
trigger:
  branch:
    exclude:
      - "production"
      - "test"
      - "levelbuilder"
  event:
    - pull_request

---
kind: pipeline
type: docker
name: trigger-github-workflow-on-droneci-success
clone:
  disable: true
steps:
  - name: trigger-gh
    image: plugins/webhook
    settings:
      urls:
        - https://api.github.com/repos/code-dot-org/code-dot-org/actions/workflows/on-droneci-complete.yml/dispatches
      username: x-access-token
      secrets:
        - source: github_token_on_droneci_success
          target: webhook_password
      template: |
        {
          "ref": "{{ build.branch }}",
          "inputs": {
            "commit": "{{ build.commit }}"
          }
        }
      debug: true
depends_on:
  - sleep-for-10s
  # - unit
  # - ui
trigger:
  event:
    - pull_request
  status:
    - success
---
kind: signature
hmac: 62f383ffbf004d67b5f6f8f2f892b50ff6120c476bbc8ad3db4ff5f2a186f8fe

...
