---
name: sleep-for-10s
kind: pipeline
type: docker
clone:
  disable: true
steps:
  - name: sleep
    image: alpine
    commands:
      - sleep 10
trigger:
  branch:
    exclude:
      - "production"
      - "test"
      - "levelbuilder"
  event:
    - pull_request

---
kind: pipeline
type: docker
name: Trigger GitHub Actions
clone:
  disable: true
steps:
  - name: Trigger on-droneci-complete.yml
    image: plugins/webhook
    settings:
      urls:
        - https://api.github.com/repos/code-dot-org/test-workflow-dispatch/actions/workflows/on-droneci-complete.yml/dispatches
      username: x-access-token
      secrets:
        - source: on-droneci-complete-github-token
          target: webhook_password
      template: |
        {
          "ref": "{{ build.branch }}",
          "inputs": {
            "github_sha": "{{ build.commit }}",
            "success": {{ if eq build.status "success" }}true{{ else }}false{{ end }}
          }
        }
      debug: true
depends_on:
  - sleep-for-10s
  # - unit
  # - ui
trigger:
  event:
    - pull_request
  status:
    - success
---
kind: signature
hmac: 66b19d8349c6b960e4dcdbe47cc2b8e2d548d810bc935c0dcc9e8f4038e6eb57

...
