---
kind: pipeline
type: docker
name: on-droneci-complete
clone:
  disable: true
steps:
  - name: print-build-status
    image: alpine
    commands:
      - echo "DRONE_BUILD_STATUS=$DRONE_BUILD_STATUS"

  - name: trigger-github-actions
    image: plugins/webhook
    settings:
      urls:
        - https://api.github.com/repos/code-dot-org/test-workflow-dispatch/actions/workflows/on-droneci-complete.yml/dispatches
      username: x-access-token
      password:
        from_secret: on-droneci-complete-github-token
      # secrets:
      #   - source: on-droneci-complete-github-token
      #     target: webhook_password
      content_type: application/json
      template: |
        {
          "ref": "{{ build.branch }}",
          "inputs": {
            "github_sha": "{{ build.commit }}",
            "drone_build_status": "{{ build.status }}",
          }
        }
      debug: true
# depends_on:
#   - unit
#   - ui
trigger:
  event:
    - pull_request
---
kind: signature
hmac: a2f6c1da8f148ba1662efa0924bae18ab2ec9504f83808ae6fb6544584e286ee

...
