---
kind: pipeline
type: docker
name: on-droneci-complete
clone:
  disable: true
steps:
  - name: trigger-github-actions
    image: plugins/webhook
    settings:
      urls:
        - https://api.github.com/repos/code-dot-org/test-workflow-dispatch/actions/workflows/on-droneci-complete.yml/dispatches
      password:
        from_secret: on-droneci-complete-github-token
      template: |
        {
          "ref": "{{ build.branch }}",
          "inputs": {
            "github_sha": "{{ build.commit }}",
            "drone_build_status": "{{ build.status }}"
          }
        }
      debug: true
# depends_on:
#   - unit
#   - ui
trigger:
  event:
    - pull_request
---
kind: signature
hmac: 00bf975fb7ec8f2fd04d17334f1437085a3d81c0fec42bb22b2a307f77359b13

...
